### ISSUE TITLE
W'all recovery issues (softlock)

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#107]
Yeah so sometimes when W'all lands recovery and hitboxes don't die before hitting the ground the game gets this error:
```
Exception in thread "Thread-6" java.util.EmptyStackException
	at java.util.Stack.peek(Unknown Source)
	at characters.Character.endState(Character.java:115)
	at characters.WallTheEncircler$6.bounce(WallTheEncircler.java:490)
	at characters.WallTheEncircler$6.onUpdate(WallTheEncircler.java:500)
	at characters.characterStates.CharacterState.update(CharacterState.java:216)
	at characters.Character.update(Character.java:456)
	at program.PlayerController.update(PlayerController.java:390)
	at program.Battle.update(Battle.java:106)
	at program.Battle.gameLoop(Battle.java:204)
	at program.Battle.access$0(Battle.java:168)
	at program.Battle$1.run(Battle.java:118)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by lgtyqz** [comment]
Yeet fixed by latest commit
